import { EntryType } from "./enums";
import { IContentPack } from "./util/unpacking/packed-types";
export declare const PACK_SCOPE = "world";
export declare function clearAll(v1?: boolean): Promise<void>;
export declare function importCP(cp: IContentPack, progress_callback?: (done: number, out_of: number) => void): Promise<void>;
export declare let IS_IMPORTING: boolean;
export declare function setAllLock(lock?: boolean, v1?: boolean): Promise<void>;
/**
 * Wipe data from all compendiums generated by the system
 * @param options Options to configure behaviour
 * @param options.v1 Whether to clear v1 data
 */
export declare function clearCompendiumData(options?: {
    v1: boolean;
}): Promise<void>;
declare global {
    interface FlagConfig {
        Folder: {
            lancer: {
                entrytype: EntryType;
            };
        };
    }
}
